[cli]
server_protocol = "http"
server_host = "localhost"
server_port = "8080"

[database]
user = "defaultuser"
password = "defaultpassword"
server = "default-db"
port = "5432"
db = "default_db"

[logging]
destination = ""
level = "INFO"
serialization = ""

[user]
analytics_opt_out = true
