name: Fides CD

# Run the check every time a new commit hits the default branch
on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  fides_cd:
    runs-on: ubuntu-latest
    container:
      image: ethyca/fides:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Nox
        run: nox
      - name: Evaluation
        run: nox
        env:
          FIDES__CLI__SERVER_HOST: "fides.privacyco.com"
