name: Fides CD

# Run the check every time a new commit hits the default branch
on:
  push:
    branches:
      - main
    tags:
      - "*"
env:
  IMAGE: ethyca/fides:local
  DEFAULT_PYTHON_VERSION: "3.8"
  #DEFAULT_PYTHON_VERSION: "3.10.8"
  #DEFAULT_PYTHON_VERSION: "3.9.14"

jobs:
  fides_cd:
    runs-on: ubuntu-latest
    container:
      image: ethyca/fides:latest
    steps:
      - name: Get Ubuntu Version
        run: cat /etc/os-release
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install LSB Release
        run: apt-get update && apt-get install -y lsb-release && apt-get clean all
      - name: LSB Release
        run: lsb_release -a
      - name: Install Python3.8
        run: apt update -y && apt upgrade -y && wget https://www.python.org/ftp/python/3.8.12/Python-3.8.12.tar.xz && tar -xf Python-3.8.12.tar.xz && mv Python3.8.12 /opt/Python3.8.12 
      - name: Install Deps
        run: apt install build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libsqlite3-dev libreadline-dev libffi-dev curl libbz2-dev -y
      - name: Build Python3.8
        run: cd /opt/Python3.8.12/ && ./configure --enable-optimizations --enable-shared && make
      - name: Make Python
        run: make altinstall && ldconfig /opt/Python3.8.12 && python3.8 –version
      - name: Install PyPi
        run: wget https://bootstrap.pypa.io/get-pip.py && python3.8 get-pip.py && python3.8 -m pip install --upgrade pip && pip3.8 --version
#      - name: Get Ubuntu Version
#      - name: Set Up Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: ${{ env.DEFAULT_PYTHON_VERSION }}
#          cache: "pip"
      - name: Python Version
        run: python -V
      - name: Update PIP
        run: python -m pip install --upgrade pip
      - name: PIP Version after upgrade
        run: pip --version
      - name: Install reqs
        run: pip install -r requirements.txt
#      - name: Install Nox
#        run: pip install nox>=2022
#      - name: Install Toml
#        run: pip install toml>=0.10
#      - name: Install Loguru
#        run: pip install loguru
#      - name: Install pydantic
#        run: pip install pydantic
      - name: Evaluation
        run: fides evaluate .fides/
        env:
          FIDES__CLI__SERVER_HOST: "fides.privacyco.com"
