name: Fides CD

# Run the check every time a new commit hits the default branch
on:
  push:
    branches:
      - main
    tags:
      - "*"
env:
  IMAGE: ethyca/fides:local
  #DEFAULT_PYTHON_VERSION: "3.10.8"
  #DEFAULT_PYTHON_VERSION: "3.9.14"

jobs:
  fides_cd:
    runs-on: ubuntu-latest
    container:
      image: ethyca/fides:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.DEFAULT_PYTHON_VERSION }}
          cache: "pip"
      - name: Python Version
        run: python -v; pip -v
      - name: Update PIP
        run: python -m pip install --upgrade pip
      - name: PIP Version after upgrade
        run: pip -v
      - name: Install reqs
        run: pip install -r requirements.txt
#      - name: Install Nox
#        run: pip install nox>=2022
#      - name: Install Toml
#        run: pip install toml>=0.10
#      - name: Install Loguru
#        run: pip install loguru
#      - name: Install pydantic
#        run: pip install pydantic
      - name: Evaluation
        run: fides evaluate .fides/
        env:
          FIDES__CLI__SERVER_HOST: "fides.privacyco.com"
