name: CI

on:
  push:
    branches:
    - main
    tags:
      - "*"
  pull_request:

jobs:
  testing:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: "pip"
    - name: Update pip
      run: python -m pip install -U pip
    - name: Install dependencies
      run: python -m pip install ethyca-fides
    - name: Evaluation
      run: fides evaluate .fides/
